// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/matryer/moq/pkg/moq/testpackages/multisrc/cache"
	"github.com/matryer/moq/pkg/moq/testpackages/multisrc/store"
	"sync"
)

// Ensure, that StoreMock does implement store.Store.
// If this is not the case, regenerate this file with moq.
var _ store.Store = &StoreMock{}

// StoreMock is a mock implementation of store.Store.
//
//	func TestSomethingThatUsesStore(t *testing.T) {
//
//		// make and configure a mocked store.Store
//		mockedStore := &StoreMock{
//			GetFunc: func(ctx context.Context, id string) (*store.Item, error) {
//				panic("mock out the Get method")
//			},
//			SaveFunc: func(ctx context.Context, item *store.Item) error {
//				panic("mock out the Save method")
//			},
//		}
//
//		// use mockedStore in code that requires store.Store
//		// and then make assertions.
//
//	}
type StoreMock struct {
	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, id string) (*store.Item, error)

	// SaveFunc mocks the Save method.
	SaveFunc func(ctx context.Context, item *store.Item) error

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// Save holds details about calls to the Save method.
		Save []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Item is the item argument value.
			Item *store.Item
		}
	}
	lockGet  sync.RWMutex
	lockSave sync.RWMutex
}

// Get calls GetFunc.
func (mock *StoreMock) Get(ctx context.Context, id string) (*store.Item, error) {
	if mock.GetFunc == nil {
		panic("StoreMock.GetFunc: method is nil but Store.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedStore.GetCalls())
func (mock *StoreMock) GetCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// Save calls SaveFunc.
func (mock *StoreMock) Save(ctx context.Context, item *store.Item) error {
	if mock.SaveFunc == nil {
		panic("StoreMock.SaveFunc: method is nil but Store.Save was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Item *store.Item
	}{
		Ctx:  ctx,
		Item: item,
	}
	mock.lockSave.Lock()
	mock.calls.Save = append(mock.calls.Save, callInfo)
	mock.lockSave.Unlock()
	return mock.SaveFunc(ctx, item)
}

// SaveCalls gets all the calls that were made to Save.
// Check the length with:
//
//	len(mockedStore.SaveCalls())
func (mock *StoreMock) SaveCalls() []struct {
	Ctx  context.Context
	Item *store.Item
} {
	var calls []struct {
		Ctx  context.Context
		Item *store.Item
	}
	mock.lockSave.RLock()
	calls = mock.calls.Save
	mock.lockSave.RUnlock()
	return calls
}

// Ensure, that CacheMock does implement cache.Cache.
// If this is not the case, regenerate this file with moq.
var _ cache.Cache = &CacheMock{}

// CacheMock is a mock implementation of cache.Cache.
//
//	func TestSomethingThatUsesCache(t *testing.T) {
//
//		// make and configure a mocked cache.Cache
//		mockedCache := &CacheMock{
//			GetFunc: func(key string) (string, bool) {
//				panic("mock out the Get method")
//			},
//			PutFunc: func(key string, value string)  {
//				panic("mock out the Put method")
//			},
//		}
//
//		// use mockedCache in code that requires cache.Cache
//		// and then make assertions.
//
//	}
type CacheMock struct {
	// GetFunc mocks the Get method.
	GetFunc func(key string) (string, bool)

	// PutFunc mocks the Put method.
	PutFunc func(key string, value string)

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// Key is the key argument value.
			Key string
		}
		// Put holds details about calls to the Put method.
		Put []struct {
			// Key is the key argument value.
			Key string
			// Value is the value argument value.
			Value string
		}
	}
	lockGet sync.RWMutex
	lockPut sync.RWMutex
}

// Get calls GetFunc.
func (mock *CacheMock) Get(key string) (string, bool) {
	if mock.GetFunc == nil {
		panic("CacheMock.GetFunc: method is nil but Cache.Get was just called")
	}
	callInfo := struct {
		Key string
	}{
		Key: key,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(key)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedCache.GetCalls())
func (mock *CacheMock) GetCalls() []struct {
	Key string
} {
	var calls []struct {
		Key string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// Put calls PutFunc.
func (mock *CacheMock) Put(key string, value string) {
	if mock.PutFunc == nil {
		panic("CacheMock.PutFunc: method is nil but Cache.Put was just called")
	}
	callInfo := struct {
		Key   string
		Value string
	}{
		Key:   key,
		Value: value,
	}
	mock.lockPut.Lock()
	mock.calls.Put = append(mock.calls.Put, callInfo)
	mock.lockPut.Unlock()
	mock.PutFunc(key, value)
}

// PutCalls gets all the calls that were made to Put.
// Check the length with:
//
//	len(mockedCache.PutCalls())
func (mock *CacheMock) PutCalls() []struct {
	Key   string
	Value string
} {
	var calls []struct {
		Key   string
		Value string
	}
	mock.lockPut.RLock()
	calls = mock.calls.Put
	mock.lockPut.RUnlock()
	return calls
}
